field: 4ef510b3-2272-43aa-b249-c7feb612f002 # Social Media Links
fieldLayouts:
  ae6cbfcf-2f74-4137-8655-f4458bce43f6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 12982b04-bf9b-48e4-8d73-c1344204d9b7 # Short Name
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 356552af-d4b4-4c5c-a3b1-2554164703c4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 347fc6c8-ef47-4e04-bcea-a2c37cd0debc # Account URL
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9bbada30-6880-4567-b6ec-d0e6efdcd281
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4e61b720-0c62-4cb2-99c7-a2ebfd12e623
        userCondition: null
fields:
  347fc6c8-ef47-4e04-bcea-a2c37cd0debc: # Account URL
    columnSuffix: jpgkzzhe
    contentColumnType: string(1000)
    fieldGroup: null
    handle: itemLink
    instructions: null
    name: 'Account URL'
    searchable: false
    settings:
      maxLength: 1000
      types:
        - url
        - tel
        - email
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  12982b04-bf9b-48e4-8d73-c1344204d9b7: # Short Name
    columnSuffix: wkzoplka
    contentColumnType: string(120)
    fieldGroup: null
    handle: itemTitle
    instructions: 'This should be a one-word key that will be used as the name of the icon'
    name: 'Short Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: 30
      code: true
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: blockAccount
name: 'Social Media Account'
sortOrder: 1
