fieldLayouts:
  42661760-44e1-4711-b64b-d9657f56a28b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: 'Full Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6c89f365-bc0f-4f1b-a64d-32c9c341dc7b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 45d4b09a-8975-4643-9e53-117ccabdcdc0 # Job Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f452b95c-d512-4477-842b-bd6bdf4f9369
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 7c07df6a-cc67-4027-bb02-932119fb7c9d # Team Member Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d80a838-e209-4351-b0a2-c1fa8a5b8304
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: a593ad16-4e29-4efe-ae8d-2b23f55af1ce # Summary
            instructions: null
            label: Bio
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67abd59c-8b52-4630-8da7-439f9c9254f8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0b7c6759-b679-47a2-b2c6-a86ddee7baeb
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 079ba75a-85f6-40a0-a4e2-f35c624860b4 # Team Members
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
