columnSuffix: null
contentColumnType: string
fieldGroup: 164558fd-6662-415b-86d8-bfc72bbbddc7 # Global
handle: assetLogoMain
instructions: null
name: 'Main Logo'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: true
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:2c79ab96-cdb4-4f4d-b481-9137d17ee4d8' # Image Files
  defaultUploadLocationSubpath: branding
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: 1
  previewMode: full
  restrictFiles: true
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:2c79ab96-cdb4-4f4d-b481-9137d17ee4d8' # Image Files
  restrictedLocationSubpath: branding
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
