columnSuffix: null
contentColumnType: string
fieldGroup: 46ef28c2-314a-409e-8fb4-cec188ecd9bb # Team
handle: fieldTeamImage
instructions: null
name: 'Team Member Image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: true
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:2c79ab96-cdb4-4f4d-b481-9137d17ee4d8' # Image Files
  defaultUploadLocationSubpath: team
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: 0
  previewMode: full
  restrictFiles: true
  restrictLocation: true
  restrictedDefaultUploadSubpath: '{slug}'
  restrictedLocationSource: 'volume:2c79ab96-cdb4-4f4d-b481-9137d17ee4d8' # Image Files
  restrictedLocationSubpath: team
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:2c79ab96-cdb4-4f4d-b481-9137d17ee4d8' # Image Files
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
