columnSuffix: haeonvqk
contentColumnType: text
fieldGroup: 794caefa-4c9a-4eca-8f28-00d0f726f290 # Common
handle: fieldSummary
instructions: null
name: Summary
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 1a4c79b2-ddf3-4b72-95e7-852ab2ff7a8e # Basic Text
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
