defaultPlacement: end
enableVersioning: true
handle: singleGlobalContent
name: 'Global Content'
propagationMethod: all
siteSettings:
  a546404d-d266-44e4-8043-45f37c896067: # GigaDB CMS
    enabledByDefault: true
    hasUrls: true
    template: global-content/_entry
    uriFormat: global-content
type: single
